### ISSUE TITLE
Umlauts are not indexed properly

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-vocabs#164]
1. Umlauts at the beginning of a string are ignored. For example go to https://w3id.org/kim/hochschulfaechersystematik/scheme and type in "Über", this is what you get:
![image](https://user-images.githubusercontent.com/160292/147063752-33565b9b-2e1b-4883-bc56-d60f0b436180.png)
2. Although we do not use a forward tokenizer yet (see #153), words that do not start with but contain an Umlaut are indexed ad two words, resulting e.g. in something like this when typing "ühgesch" or "hgesch" at https://w3id.org/kim/hochschulfaechersystematik/scheme:
![image](https://user-images.githubusercontent.com/160292/147064806-16e63c0e-754e-48a8-8fa1-98d0e8f50a09.png)

**Comment by acka47** [comment]
#186 is now deployed on test and I let this build anew: https://test.skohub.io/acka47/testing-skohub-vocabs/heads/master/index.de.html 

Umlauts now don't work in a different way than before:

![image](https://user-images.githubusercontent.com/160292/182402539-1c2a0d88-31d1-4368-be23-5e6dda55bd23.png)

Theay are apparantly not ignored anymore but transformed to their corresponding vowel:

![image](https://user-images.githubusercontent.com/160292/182402816-1961a1fd-4755-4597-8fcc-0903d493d474.png)

**Comment by sroertgen** [comment]
As mentioned in https://github.com/skohub-io/skohub-vocabs/pull/197#issue-1326736011 Uppercase umlaute should now work.

> Theay are apparantly not ignored anymore but transformed to their corresponding vowel:

This is still the case and requires some adjustments in either `App.js` or the `nestedList.js` component. So #197 will not close this issue. But it will bring some improvement.

**Comment by acka47** [comment]
Functional review for #197:

As @sroertgen says, this is an improvement as upper case Umlauts now also work (I noticed that my "Über" example in https://github.com/skohub-io/skohub-vocabs/issues/164#issuecomment-1202724985 isn't a good one as there eists no "Über" in the Hochschulfächerklassifikation):
![image](https://user-images.githubusercontent.com/160292/183363911-d955f1ed-440c-47f7-b519-12f9e5369b89.png)

The change from #197 can be deployed to production, I will open a PR against the master. Otherwise I agree with @sroertgen that this will need some more work to close the issue by handling Umlaute correctly.

**Comment by acka47** [comment]
Reopening as #197 doesn't completely fix the problem (see above two comments by me and @sroertgen ).
